### PR TITLE
Removes rel attribute

### LINKED ISSUE #76: I cannot create .htaccess rules for the download (no HTTP_REFERER)
I would like to prohibit access via the direct link to a file. The attachments should only be downloadable via the page with the content.

-----------------------------------------

Content is available here:
domain-xyz.com/folder/article123

Uploads are uploaded here (location of the .htaccess)
domain-xyz.com/uploads/

.htaccess example

```
RewriteEngine On
# Allows access only from the domain+folder domain-xyz.com/folder/*
RewriteCond %{HTTP_REFERER} !^https?://(www\.)?domain-xyz\.com/folder/ [NC]
RewriteRule ^ - [F]
```

-----------------------------------------

All manual added links (to the file eg https://domain-xyz.com/uploads/xx12345.pdf) in the editor text works correctly:

(a)
When I click on the download link from the article, I get to the file. As soon as I call up the URL to the file manually, I get a 403.

(b)
Unfortunately, I always get a 403 when downloading via the element of attaches in the article.  When downloading there is probably no HTTP_REFERER and therefore the restriction in the .htaccess fails.

-----------------------------------------

Am I doing something wrong, is it a bug or currently not possible?

### PR DESCRIPTION
**Pull request by bettysteger**
Fixes https://github.com/editor-js/attaches/issues/76 

Removes the `rel` attribute from the `a`-tag
====

**Explanations:**

There is no "noindex" value for the [rel](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/rel) HTML attribute. 

The [nofollow attribute ](https://ahrefs.com/seo/glossary/nofollow) was used in the past to tell search engines to simply ignore a link. Google would not crawl these links and did not pass value through them. Their treatment of nofollow links changed in 2020 and now it’s more complicated. They treat nofollow as a hint, which means they can choose to crawl and pass value through them, or not.

[Noreferrer](https://ahrefs.com/seo/glossary/noreferrer) is related to analytics and tracking. The referrer value shows the previous page where a user came from. By using the noreferrer attribute on a link, you are preventing other pages from seeing that traffic came from a click on your link.

→ Some APIs do validate the referer to access a file and so we can remove that value.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -437,11 +437,23 @@ export default class AttachesTool {
...
+        this.nodes.wrapper.addEventListener('click', (event) => {
+          // Don't trigger if clicking on the actual download link
+          if (event.target.closest(`.${this.CSS.downloadButton}`)) {
+            return;
+          }
+          // Open file in new tab/window
+          window.open(file.url, '_blank');
+        });
+      }
+
```
Comment (neSpecc) [inline src/index.js]: seems like these changes are not related to the original issue.

File: src/index.js [hunk 2]
```diff
@@ -437,11 +437,23 @@ export default class AttachesTool {
...
       const downloadIcon = make('a', this.CSS.downloadButton, {
         innerHTML: IconChevronDown,
         href: file.url,
         target: '_blank',
-        rel: 'nofollow noindex noreferrer',
```
Comment (neSpecc) [inline src/index.js:444]: explain the problem and the fix please in the PR description.

Also, please update a patch version

**Review by neSpecc — CHANGES_REQUESTED** [review]

File: src/index.js (hunk 1 above)
Comment (bettysteger) [reply src/index.js]: sorry, no i added this later - i will move this to another branch

File: src/index.js (hunk 2 above)
Comment (bettysteger) [reply src/index.js:444]: done!

**Review by neSpecc — APPROVED** [review]
